[build]
builder = "NIXPACKS"

[nixpacks]
nixpacksPlan = '''
{
  "phases": {
    "setup": {
      "nixPkgs": ["python39"]
    },
    "install": {
      "cmds": ["cd lotto_backend && pip install -r requirements.txt"]
    }
  },
  "start": {
    "cmd": "cd lotto_backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
  }
}
'''